// <auto-generated />
namespace vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class populate_membership_type : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(populate_membership_type));
        
        string IMigrationMetadata.Id
        {
            get { return "202109190845376_populate_membership_type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
