// <auto-generated />
namespace vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_annotations_to_base_model_name : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_annotations_to_base_model_name));
        
        string IMigrationMetadata.Id
        {
            get { return "202109190901448_add_annotations_to_base_model_name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
