// <auto-generated />
namespace vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class track_number_of_available_movies_for_rent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(track_number_of_available_movies_for_rent));
        
        string IMigrationMetadata.Id
        {
            get { return "202109292347475_track_number_of_available_movies_for_rent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
