// <auto-generated />
namespace vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_createdOn_and_updatedOn_to_baseModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_createdOn_and_updatedOn_to_baseModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202109200923193_add_createdOn_and_updatedOn_to_baseModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
